# Uncomment the next line to define a global platform for your project
platform :ios, '10.2'

target 'BGXCommander' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for BGXCommander

  pod 'MMDrawerController', '~> 0.5.7'

  pod 'PullToRefresh', '~> 0.0'

  pod 'bgxpress', :path => '../..' 

  target 'BGXCommanderTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BGXCommanderUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
