# Uncomment the next line to define a global platform for your project
platform :ios, '10.2'

target 'BGXCommander' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for BGXCommander

  post_install do |installer|

  puts 'Determining pod project minimal deployment target'

  pods_project = installer.pods_project
  deployment_target_key = 'IPHONEOS_DEPLOYMENT_TARGET'
  deployment_targets = pods_project.build_configurations.map{ |config| config.build_settings[deployment_target_key] }
  minimal_deployment_target = deployment_targets.min_by{ |version| Gem::Version.new(version) }

  puts 'Minimal deployment target is ' + minimal_deployment_target
  puts 'Setting each pod deployment target to ' + minimal_deployment_target
  
  installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
          config.build_settings[deployment_target_key] = minimal_deployment_target
      end
  end
  end
  
  pod 'MMDrawerController', '~> 0.5.7'

  pod 'PullToRefresh', '~> 0.0'

  pod 'bgxpress', :path => '../..' 

  target 'BGXCommanderTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BGXCommanderUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
